# Generated by Django 5.1.3 on 2024-11-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_alter_memory_descript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='descript',
            new_name='description',
        ),
    ]
