# Generated by Django 5.1.3 on 2024-11-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='image',
        ),
        migrations.AddField(
            model_name='memory',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='memories'),
        ),
    ]
