# Generated by Django 5.1.3 on 2024-11-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_remove_memory_image_memory_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
